create table person(
   id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name varchar NOT NULL,
   age int CHECK ( age > 0 ),
   email varchar UNIQUE
);

insert into person(name, age, email)
values ('Bob', 25, 'bob@ya.ru'),
       ('Tom', 31, 'tom@ya.ru'),
       ('John', 53, 'john2@ya.ru'),
       ('Marry', 20, 'marry@ya.ru'),
       ('Katty', 14, 'katty3@ya.ru');

select * FROM person;
select * FROM item;

drop table person;
drop table item;

CREATE TABLE item(
       id int generated by default as identity primary key,
       person_id int references person(id) on delete set null,
       item_name varchar(128) not null
);

insert into item (person_id, item_name)
values (1, 'Airpods'),
       (1, 'Playstation'),
       (1, 'TV');


